export type SettingsProvider =
  | "groq"
  | "google"
  | "anthropic"
  | "openai"
  | "openrouter";

export type ProviderModel = {
  id: string;
  provider: SettingsProvider;
  name: string;
  apiModelId: string;
  hasReasoning: boolean;
  canDisableThinking: boolean;
};

const MODELS: ProviderModel[] = [
  {
    id: "groq-compound-beta",
    provider: "groq",
    name: "Compound Beta",
    apiModelId: "compound-beta",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "groq-compound-beta-mini",
    provider: "groq",
    name: "Compound Beta Mini",
    apiModelId: "compound-beta-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "groq-deepseek-r1-70b",
    provider: "groq",
    name: "DeepSeek R1 70B",
    apiModelId: "deepseek-r1-distill-llama-70b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "groq-gpt-oss-120b",
    provider: "groq",
    name: "GPT-OSS 120B",
    apiModelId: "openai/gpt-oss-120b",
    hasReasoning: true,
    canDisableThinking: false,
  },
  {
    id: "groq-gpt-oss-20b",
    provider: "groq",
    name: "GPT-OSS 20B",
    apiModelId: "openai/gpt-oss-20b",
    hasReasoning: true,
    canDisableThinking: false,
  },
  {
    id: "groq-kimi-k2",
    provider: "groq",
    name: "Kimi K2",
    apiModelId: "moonshotai/kimi-k2-instruct-0905",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "groq-llama-3.3-70b",
    provider: "groq",
    name: "Llama 3.3 70B",
    apiModelId: "llama-3.3-70b-versatile",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "groq-llama-4-maverick-17b",
    provider: "groq",
    name: "Llama 4 Maverick 17B",
    apiModelId: "meta-llama/llama-4-maverick-17b-128e-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "groq-llama-4-scout-17b",
    provider: "groq",
    name: "Llama 4 Scout 17B",
    apiModelId: "meta-llama/llama-4-scout-17b-16e-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "groq-qwen-qwq-32b",
    provider: "groq",
    name: "Qwen QwQ 32B",
    apiModelId: "qwen/qwen3-32b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-1.5-flash",
    provider: "google",
    name: "Gemini 1.5 Flash",
    apiModelId: "gemini-1.5-flash-002",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-1.5-pro",
    provider: "google",
    name: "Gemini 1.5 Pro",
    apiModelId: "gemini-1.5-pro-002",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-2.0-flash",
    provider: "google",
    name: "Gemini 2.0 Flash",
    apiModelId: "gemini-2.0-flash",
    hasReasoning: true,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-2.0-flash-lite",
    provider: "google",
    name: "Gemini 2.0 Flash Lite",
    apiModelId: "gemini-2.0-flash-lite",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-2.0-pro",
    provider: "google",
    name: "Gemini 2.0 Pro",
    apiModelId: "gemini-2.0-pro-exp",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-2.5-flash",
    provider: "google",
    name: "Gemini 2.5 Flash",
    apiModelId: "gemini-2.5-flash",
    hasReasoning: true,
    canDisableThinking: true,
  },
  {
    id: "googleai-gemini-2.5-flash-lite",
    provider: "google",
    name: "Gemini 2.5 Flash Lite",
    apiModelId: "gemini-2.5-flash-lite-preview-06-17",
    hasReasoning: true,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-2.5-flash-preview",
    provider: "google",
    name: "Gemini 2.5 Flash Preview (Image Gen)",
    apiModelId: "gemini-2.5-flash-image-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-2.5-pro",
    provider: "google",
    name: "Gemini 2.5 Pro",
    apiModelId: "gemini-2.5-pro",
    hasReasoning: true,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-2.5-pro-preview",
    provider: "google",
    name: "Gemini 2.5 Pro Preview",
    apiModelId: "gemini-2.5-pro-preview-06-05",
    hasReasoning: true,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemini-exp",
    provider: "google",
    name: "Gemini Experimental",
    apiModelId: "gemini-exp-1206",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "googleai-gemma-3-27b",
    provider: "google",
    name: "Gemma 3 27B",
    apiModelId: "gemma-3-27b-it",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "anthropic-claude-3-haiku",
    provider: "anthropic",
    name: "Claude Haiku 3",
    apiModelId: "claude-3-haiku-20240307",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "anthropic-claude-3.5-haiku",
    provider: "anthropic",
    name: "Claude Haiku 3.5",
    apiModelId: "claude-3-5-haiku-20241022",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "anthropic-claude-4-opus",
    provider: "anthropic",
    name: "Claude Opus 4",
    apiModelId: "claude-opus-4-20250514",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "anthropic-claude-opus-4.1",
    provider: "anthropic",
    name: "Claude Opus 4.1",
    apiModelId: "claude-opus-4-1-20250805",
    hasReasoning: true,
    canDisableThinking: true,
  },
  {
    id: "anthropic-claude-3.5-sonnet",
    provider: "anthropic",
    name: "Claude Sonnet 3.5",
    apiModelId: "claude-3-5-sonnet-latest",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "anthropic-claude-3.7-sonnet",
    provider: "anthropic",
    name: "Claude Sonnet 3.7",
    apiModelId: "claude-3-7-sonnet-20250219",
    hasReasoning: true,
    canDisableThinking: true,
  },
  {
    id: "anthropic-claude-4-sonnet",
    provider: "anthropic",
    name: "Claude Sonnet 4",
    apiModelId: "claude-sonnet-4-20250514",
    hasReasoning: true,
    canDisableThinking: true,
  },
  {
    id: "openai-chatgpt-4o",
    provider: "openai",
    name: "ChatGPT 4o",
    apiModelId: "chatgpt-4o-latest",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-4.1",
    provider: "openai",
    name: "GPT-4.1",
    apiModelId: "gpt-4.1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-4.1-mini",
    provider: "openai",
    name: "GPT-4.1 Mini",
    apiModelId: "gpt-4.1-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-4.1-nano",
    provider: "openai",
    name: "GPT-4.1 Nano",
    apiModelId: "gpt-4.1-nano",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-4.5",
    provider: "openai",
    name: "GPT-4.5 (Preview)",
    apiModelId: "gpt-4.5-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-4o",
    provider: "openai",
    name: "GPT-4o",
    apiModelId: "openai-gpt-4o",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-4o-audio",
    provider: "openai",
    name: "GPT-4o Audio",
    apiModelId: "gpt-4o-audio-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-4o-mini",
    provider: "openai",
    name: "GPT-4o Mini",
    apiModelId: "openai-gpt-4o-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-5",
    provider: "openai",
    name: "GPT-5",
    apiModelId: "gpt-5",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-5-chat",
    provider: "openai",
    name: "GPT-5 Chat",
    apiModelId: "gpt-5-chat-latest",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-5-mini",
    provider: "openai",
    name: "GPT-5 mini",
    apiModelId: "gpt-5-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-gpt-5-nano",
    provider: "openai",
    name: "GPT-5 nano",
    apiModelId: "gpt-5-nano",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o1",
    provider: "openai",
    name: "o1",
    apiModelId: "o1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o1-mini",
    provider: "openai",
    name: "o1 mini",
    apiModelId: "o1-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o1-preview",
    provider: "openai",
    name: "o1 preview",
    apiModelId: "o1-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o1-pro",
    provider: "openai",
    name: "o1 pro",
    apiModelId: "o1-pro",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o3",
    provider: "openai",
    name: "o3",
    apiModelId: "o3",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o3-deep-research",
    provider: "openai",
    name: "o3 deep research",
    apiModelId: "o3-deep-research",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o3-mini",
    provider: "openai",
    name: "o3 mini",
    apiModelId: "o3-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o3-pro",
    provider: "openai",
    name: "o3 pro",
    apiModelId: "o3-pro",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o4-mini",
    provider: "openai",
    name: "o4 mini",
    apiModelId: "o4-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openai-o4-mini-deep-research",
    provider: "openai",
    name: "o4 mini deep research",
    apiModelId: "o4-mini-deep-research",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-agentica-org-deepcoder-14b-preview",
    provider: "openrouter",
    name: "Agentica: Deepcoder 14B Preview (free)",
    apiModelId: "agentica-org/deepcoder-14b-preview:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-ai21-jamba-large-1-7",
    provider: "openrouter",
    name: "AI21: Jamba Large 1.7",
    apiModelId: "ai21/jamba-large-1.7",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-ai21-jamba-mini-1-7",
    provider: "openrouter",
    name: "AI21: Jamba Mini 1.7",
    apiModelId: "ai21/jamba-mini-1.7",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-aion-labs-aion-1-0",
    provider: "openrouter",
    name: "AionLabs: Aion-1.0",
    apiModelId: "aion-labs/aion-1.0",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-aion-labs-aion-1-0-mini",
    provider: "openrouter",
    name: "AionLabs: Aion-1.0-Mini",
    apiModelId: "aion-labs/aion-1.0-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-aion-labs-aion-rp-llama-3-1-8b",
    provider: "openrouter",
    name: "AionLabs: Aion-RP 1.0 (8B)",
    apiModelId: "aion-labs/aion-rp-llama-3.1-8b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-alfredpros-codellama-7b-instruct-solidity",
    provider: "openrouter",
    name: "AlfredPros: CodeLLaMa 7B Instruct Solidity",
    apiModelId: "alfredpros/codellama-7b-instruct-solidity",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-allenai-molmo-7b-d-0924",
    provider: "openrouter",
    name: "AllenAI: Molmo 7B D",
    apiModelId: "allenai/molmo-7b-d",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-allenai-olmo-2-0325-32b-instruct",
    provider: "openrouter",
    name: "AllenAI: Olmo 2 32B Instruct",
    apiModelId: "allenai/olmo-2-0325-32b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-amazon-nova-lite-v1",
    provider: "openrouter",
    name: "Amazon: Nova Lite 1.0",
    apiModelId: "amazon/nova-lite-v1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-amazon-nova-micro-v1",
    provider: "openrouter",
    name: "Amazon: Nova Micro 1.0",
    apiModelId: "amazon/nova-micro-v1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-amazon-nova-pro-v1",
    provider: "openrouter",
    name: "Amazon: Nova Pro 1.0",
    apiModelId: "amazon/nova-pro-v1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-3-haiku",
    provider: "openrouter",
    name: "Anthropic: Claude 3 Haiku",
    apiModelId: "anthropic/claude-3-haiku",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-3-opus",
    provider: "openrouter",
    name: "Anthropic: Claude 3 Opus",
    apiModelId: "anthropic/claude-3-opus",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-3-5-haiku",
    provider: "openrouter",
    name: "Anthropic: Claude 3.5 Haiku",
    apiModelId: "anthropic/claude-3.5-haiku",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-3-5-haiku-20241022",
    provider: "openrouter",
    name: "Anthropic: Claude 3.5 Haiku (2024-10-22)",
    apiModelId: "anthropic/claude-3.5-haiku-20241022",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-3-5-sonnet",
    provider: "openrouter",
    name: "Anthropic: Claude 3.5 Sonnet",
    apiModelId: "anthropic/claude-3.5-sonnet",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-3-5-sonnet-20240620",
    provider: "openrouter",
    name: "Anthropic: Claude 3.5 Sonnet (2024-06-20)",
    apiModelId: "anthropic/claude-3.5-sonnet-20240620",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-3-7-sonnet-20250219",
    provider: "openrouter",
    name: "Anthropic: Claude 3.7 Sonnet",
    apiModelId: "anthropic/claude-3.7-sonnet",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-4-opus-20250522",
    provider: "openrouter",
    name: "Anthropic: Claude Opus 4",
    apiModelId: "anthropic/claude-opus-4",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-4-1-opus-20250805",
    provider: "openrouter",
    name: "Anthropic: Claude Opus 4.1",
    apiModelId: "anthropic/claude-opus-4.1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-4-sonnet-20250522",
    provider: "openrouter",
    name: "Anthropic: Claude Sonnet 4",
    apiModelId: "anthropic/claude-sonnet-4",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthropic-claude-4-5-sonnet-20250929",
    provider: "openrouter",
    name: "Anthropic: Claude Sonnet 4.5",
    apiModelId: "anthropic/claude-sonnet-4.5",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-arcee-ai-afm-4-5b",
    provider: "openrouter",
    name: "Arcee AI: AFM 4.5B",
    apiModelId: "arcee-ai/afm-4.5b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-arcee-ai-coder-large",
    provider: "openrouter",
    name: "Arcee AI: Coder Large",
    apiModelId: "arcee-ai/coder-large",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-arcee-ai-maestro-reasoning",
    provider: "openrouter",
    name: "Arcee AI: Maestro Reasoning",
    apiModelId: "arcee-ai/maestro-reasoning",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-arcee-ai-spotlight",
    provider: "openrouter",
    name: "Arcee AI: Spotlight",
    apiModelId: "arcee-ai/spotlight",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-arcee-ai-virtuoso-large",
    provider: "openrouter",
    name: "Arcee AI: Virtuoso Large",
    apiModelId: "arcee-ai/virtuoso-large",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-arliai-qwq-32b-arliai-rpr-v1",
    provider: "openrouter",
    name: "ArliAI: QwQ 32B RpR v1 (free)",
    apiModelId: "arliai/qwq-32b-arliai-rpr-v1:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openrouter-auto",
    provider: "openrouter",
    name: "Auto Router",
    apiModelId: "openrouter/auto",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-baidu-ernie-4-5-21b-a3b",
    provider: "openrouter",
    name: "Baidu: ERNIE 4.5 21B A3B",
    apiModelId: "baidu/ernie-4.5-21b-a3b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-baidu-ernie-4-5-300b-a47b",
    provider: "openrouter",
    name: "Baidu: ERNIE 4.5 300B A47B ",
    apiModelId: "baidu/ernie-4.5-300b-a47b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-baidu-ernie-4-5-vl-28b-a3b",
    provider: "openrouter",
    name: "Baidu: ERNIE 4.5 VL 28B A3B",
    apiModelId: "baidu/ernie-4.5-vl-28b-a3b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-baidu-ernie-4-5-vl-424b-a47b",
    provider: "openrouter",
    name: "Baidu: ERNIE 4.5 VL 424B A47B ",
    apiModelId: "baidu/ernie-4.5-vl-424b-a47b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-bytedance-seed-oss-36b-instruct",
    provider: "openrouter",
    name: "ByteDance: Seed OSS 36B Instruct",
    apiModelId: "bytedance/seed-oss-36b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-bytedance-ui-tars-1-5-7b",
    provider: "openrouter",
    name: "ByteDance: UI-TARS 7B ",
    apiModelId: "bytedance/ui-tars-1.5-7b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepcogito-cogito-v2-preview-llama-109b-moe",
    provider: "openrouter",
    name: "Cogito V2 Preview Llama 109B",
    apiModelId: "deepcogito/cogito-v2-preview-llama-109b-moe",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-cohere-command-a-03-2025",
    provider: "openrouter",
    name: "Cohere: Command A",
    apiModelId: "cohere/command-a",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-cohere-command-r-08-2024",
    provider: "openrouter",
    name: "Cohere: Command R (08-2024)",
    apiModelId: "cohere/command-r-08-2024",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-cohere-command-r-plus-08-2024",
    provider: "openrouter",
    name: "Cohere: Command R+ (08-2024)",
    apiModelId: "cohere/command-r-plus-08-2024",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-cohere-command-r7b-12-2024",
    provider: "openrouter",
    name: "Cohere: Command R7B (12-2024)",
    apiModelId: "cohere/command-r7b-12-2024",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepcogito-cogito-v2-preview-deepseek-671b",
    provider: "openrouter",
    name: "Deep Cogito: Cogito V2 Preview Deepseek 671B",
    apiModelId: "deepcogito/cogito-v2-preview-deepseek-671b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-prover-v2",
    provider: "openrouter",
    name: "DeepSeek: DeepSeek Prover V2",
    apiModelId: "deepseek/deepseek-prover-v2",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-r1-0528-qwen3-8b",
    provider: "openrouter",
    name: "DeepSeek: Deepseek R1 0528 Qwen3 8B (free)",
    apiModelId: "deepseek/deepseek-r1-0528-qwen3-8b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-chat-v3",
    provider: "openrouter",
    name: "DeepSeek: DeepSeek V3",
    apiModelId: "deepseek/deepseek-chat",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-chat-v3-0324",
    provider: "openrouter",
    name: "DeepSeek: DeepSeek V3 0324 (free)",
    apiModelId: "deepseek/deepseek-chat-v3-0324:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-chat-v3-1",
    provider: "openrouter",
    name: "DeepSeek: DeepSeek V3.1 (free)",
    apiModelId: "deepseek/deepseek-chat-v3.1:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-v3-1-base",
    provider: "openrouter",
    name: "DeepSeek: DeepSeek V3.1 Base",
    apiModelId: "deepseek/deepseek-v3.1-base",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-v3-1-terminus",
    provider: "openrouter",
    name: "DeepSeek: DeepSeek V3.1 Terminus",
    apiModelId: "deepseek/deepseek-v3.1-terminus",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-v3-2-exp",
    provider: "openrouter",
    name: "DeepSeek: DeepSeek V3.2 Exp",
    apiModelId: "deepseek/deepseek-v3.2-exp",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-r1",
    provider: "openrouter",
    name: "DeepSeek: R1 (free)",
    apiModelId: "deepseek/deepseek-r1:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-r1-0528",
    provider: "openrouter",
    name: "DeepSeek: R1 0528 (free)",
    apiModelId: "deepseek/deepseek-r1-0528:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-r1-distill-llama-70b",
    provider: "openrouter",
    name: "DeepSeek: R1 Distill Llama 70B (free)",
    apiModelId: "deepseek/deepseek-r1-distill-llama-70b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-r1-distill-llama-8b",
    provider: "openrouter",
    name: "DeepSeek: R1 Distill Llama 8B",
    apiModelId: "deepseek/deepseek-r1-distill-llama-8b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-r1-distill-qwen-14b",
    provider: "openrouter",
    name: "DeepSeek: R1 Distill Qwen 14B",
    apiModelId: "deepseek/deepseek-r1-distill-qwen-14b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-deepseek-deepseek-r1-distill-qwen-32b",
    provider: "openrouter",
    name: "DeepSeek: R1 Distill Qwen 32B",
    apiModelId: "deepseek/deepseek-r1-distill-qwen-32b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-cognitivecomputations-dolphin3-0-mistral-24b",
    provider: "openrouter",
    name: "Dolphin3.0 Mistral 24B (free)",
    apiModelId: "cognitivecomputations/dolphin3.0-mistral-24b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-cognitivecomputations-dolphin3-0-r1-mistral-24b",
    provider: "openrouter",
    name: "Dolphin3.0 R1 Mistral 24B (free)",
    apiModelId: "cognitivecomputations/dolphin3.0-r1-mistral-24b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-eleutherai-llemma-7b",
    provider: "openrouter",
    name: "EleutherAI: Llemma 7b",
    apiModelId: "eleutherai/llemma_7b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-5-flash-image-preview",
    provider: "openrouter",
    name: "Gemini 2.5 Flash Image (Nano Banana)",
    apiModelId: "google/gemini-2.5-flash-image-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-alpindale-goliath-120b",
    provider: "openrouter",
    name: "Goliath 120B",
    apiModelId: "alpindale/goliath-120b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-0-flash-001",
    provider: "openrouter",
    name: "Google: Gemini 2.0 Flash",
    apiModelId: "google/gemini-2.0-flash-001",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-0-flash-exp",
    provider: "openrouter",
    name: "Google: Gemini 2.0 Flash Experimental (free)",
    apiModelId: "google/gemini-2.0-flash-exp:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-0-flash-lite-001",
    provider: "openrouter",
    name: "Google: Gemini 2.0 Flash Lite",
    apiModelId: "google/gemini-2.0-flash-lite-001",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-5-flash",
    provider: "openrouter",
    name: "Google: Gemini 2.5 Flash",
    apiModelId: "google/gemini-2.5-flash",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-5-flash-lite",
    provider: "openrouter",
    name: "Google: Gemini 2.5 Flash Lite",
    apiModelId: "google/gemini-2.5-flash-lite",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-5-flash-lite-preview-06-17",
    provider: "openrouter",
    name: "Google: Gemini 2.5 Flash Lite Preview 06-17",
    apiModelId: "google/gemini-2.5-flash-lite-preview-06-17",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-5-flash-lite-preview-09-2025",
    provider: "openrouter",
    name: "Google: Gemini 2.5 Flash Lite Preview 09-2025",
    apiModelId: "google/gemini-2.5-flash-lite-preview-09-2025",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-5-flash-preview-09-2025",
    provider: "openrouter",
    name: "Google: Gemini 2.5 Flash Preview 09-2025",
    apiModelId: "google/gemini-2.5-flash-preview-09-2025",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-5-pro",
    provider: "openrouter",
    name: "Google: Gemini 2.5 Pro",
    apiModelId: "google/gemini-2.5-pro",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-5-pro-preview-03-25",
    provider: "openrouter",
    name: "Google: Gemini 2.5 Pro Preview 05-06",
    apiModelId: "google/gemini-2.5-pro-preview-05-06",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemini-2-5-pro-preview-06-05",
    provider: "openrouter",
    name: "Google: Gemini 2.5 Pro Preview 06-05",
    apiModelId: "google/gemini-2.5-pro-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemma-2-27b-it",
    provider: "openrouter",
    name: "Google: Gemma 2 27B",
    apiModelId: "google/gemma-2-27b-it",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemma-2-9b-it",
    provider: "openrouter",
    name: "Google: Gemma 2 9B (free)",
    apiModelId: "google/gemma-2-9b-it:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemma-3-12b-it",
    provider: "openrouter",
    name: "Google: Gemma 3 12B (free)",
    apiModelId: "google/gemma-3-12b-it:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemma-3-27b-it",
    provider: "openrouter",
    name: "Google: Gemma 3 27B (free)",
    apiModelId: "google/gemma-3-27b-it:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemma-3-4b-it",
    provider: "openrouter",
    name: "Google: Gemma 3 4B (free)",
    apiModelId: "google/gemma-3-4b-it:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemma-3n-e2b-it",
    provider: "openrouter",
    name: "Google: Gemma 3n 2B (free)",
    apiModelId: "google/gemma-3n-e2b-it:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-google-gemma-3n-e4b-it",
    provider: "openrouter",
    name: "Google: Gemma 3n 4B (free)",
    apiModelId: "google/gemma-3n-e4b-it:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-inception-mercury",
    provider: "openrouter",
    name: "Inception: Mercury",
    apiModelId: "inception/mercury",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-inception-mercury-coder-small-beta",
    provider: "openrouter",
    name: "Inception: Mercury Coder",
    apiModelId: "inception/mercury-coder",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-inflection-inflection-3-pi",
    provider: "openrouter",
    name: "Inflection: Inflection 3 Pi",
    apiModelId: "inflection/inflection-3-pi",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-inflection-inflection-3-productivity",
    provider: "openrouter",
    name: "Inflection: Inflection 3 Productivity",
    apiModelId: "inflection/inflection-3-productivity",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-liquid-lfm-3b",
    provider: "openrouter",
    name: "Liquid: LFM 3B",
    apiModelId: "liquid/lfm-3b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-liquid-lfm-7b",
    provider: "openrouter",
    name: "Liquid: LFM 7B",
    apiModelId: "liquid/lfm-7b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-guard-3-8b",
    provider: "openrouter",
    name: "Llama Guard 3 8B",
    apiModelId: "meta-llama/llama-guard-3-8b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthracite-org-magnum-v2-72b",
    provider: "openrouter",
    name: "Magnum v2 72B",
    apiModelId: "anthracite-org/magnum-v2-72b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-anthracite-org-magnum-v4-72b",
    provider: "openrouter",
    name: "Magnum v4 72B",
    apiModelId: "anthracite-org/magnum-v4-72b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mancer-weaver",
    provider: "openrouter",
    name: "Mancer: Weaver (alpha)",
    apiModelId: "mancer/weaver",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meituan-longcat-flash-chat",
    provider: "openrouter",
    name: "Meituan: LongCat Flash Chat (free)",
    apiModelId: "meituan/longcat-flash-chat:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-70b-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3 70B Instruct",
    apiModelId: "meta-llama/llama-3-70b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-8b-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3 8B Instruct",
    apiModelId: "meta-llama/llama-3-8b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-1-405b",
    provider: "openrouter",
    name: "Meta: Llama 3.1 405B (base)",
    apiModelId: "meta-llama/llama-3.1-405b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-1-405b-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3.1 405B Instruct",
    apiModelId: "meta-llama/llama-3.1-405b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-1-70b-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3.1 70B Instruct",
    apiModelId: "meta-llama/llama-3.1-70b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-1-8b-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3.1 8B Instruct",
    apiModelId: "meta-llama/llama-3.1-8b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-2-11b-vision-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3.2 11B Vision Instruct",
    apiModelId: "meta-llama/llama-3.2-11b-vision-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-2-1b-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3.2 1B Instruct",
    apiModelId: "meta-llama/llama-3.2-1b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-2-3b-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3.2 3B Instruct (free)",
    apiModelId: "meta-llama/llama-3.2-3b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-2-90b-vision-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3.2 90B Vision Instruct",
    apiModelId: "meta-llama/llama-3.2-90b-vision-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-3-70b-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3.3 70B Instruct (free)",
    apiModelId: "meta-llama/llama-3.3-70b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-3-3-8b-instruct",
    provider: "openrouter",
    name: "Meta: Llama 3.3 8B Instruct (free)",
    apiModelId: "meta-llama/llama-3.3-8b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-4-maverick-17b-128e-instruct",
    provider: "openrouter",
    name: "Meta: Llama 4 Maverick (free)",
    apiModelId: "meta-llama/llama-4-maverick:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-4-scout-17b-16e-instruct",
    provider: "openrouter",
    name: "Meta: Llama 4 Scout (free)",
    apiModelId: "meta-llama/llama-4-scout:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-guard-4-12b",
    provider: "openrouter",
    name: "Meta: Llama Guard 4 12B",
    apiModelId: "meta-llama/llama-guard-4-12b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-meta-llama-llama-guard-2-8b",
    provider: "openrouter",
    name: "Meta: LlamaGuard 2 8B",
    apiModelId: "meta-llama/llama-guard-2-8b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-microsoft-mai-ds-r1",
    provider: "openrouter",
    name: "Microsoft: MAI DS R1 (free)",
    apiModelId: "microsoft/mai-ds-r1:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-microsoft-phi-4",
    provider: "openrouter",
    name: "Microsoft: Phi 4",
    apiModelId: "microsoft/phi-4",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-microsoft-phi-4-multimodal-instruct",
    provider: "openrouter",
    name: "Microsoft: Phi 4 Multimodal Instruct",
    apiModelId: "microsoft/phi-4-multimodal-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-microsoft-phi-4-reasoning-plus-04-30",
    provider: "openrouter",
    name: "Microsoft: Phi 4 Reasoning Plus",
    apiModelId: "microsoft/phi-4-reasoning-plus",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-microsoft-phi-3-medium-128k-instruct",
    provider: "openrouter",
    name: "Microsoft: Phi-3 Medium 128K Instruct",
    apiModelId: "microsoft/phi-3-medium-128k-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-microsoft-phi-3-mini-128k-instruct",
    provider: "openrouter",
    name: "Microsoft: Phi-3 Mini 128K Instruct",
    apiModelId: "microsoft/phi-3-mini-128k-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-microsoft-phi-3-5-mini-128k-instruct",
    provider: "openrouter",
    name: "Microsoft: Phi-3.5 Mini 128K Instruct",
    apiModelId: "microsoft/phi-3.5-mini-128k-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-minimax-minimax-m1",
    provider: "openrouter",
    name: "MiniMax: MiniMax M1",
    apiModelId: "minimax/minimax-m1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-minimax-minimax-01",
    provider: "openrouter",
    name: "MiniMax: MiniMax-01",
    apiModelId: "minimax/minimax-01",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-large",
    provider: "openrouter",
    name: "Mistral Large",
    apiModelId: "mistralai/mistral-large",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-large-2407",
    provider: "openrouter",
    name: "Mistral Large 2407",
    apiModelId: "mistralai/mistral-large-2407",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-large-2411",
    provider: "openrouter",
    name: "Mistral Large 2411",
    apiModelId: "mistralai/mistral-large-2411",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-small",
    provider: "openrouter",
    name: "Mistral Small",
    apiModelId: "mistralai/mistral-small",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-tiny",
    provider: "openrouter",
    name: "Mistral Tiny",
    apiModelId: "mistralai/mistral-tiny",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-codestral-2501",
    provider: "openrouter",
    name: "Mistral: Codestral 2501",
    apiModelId: "mistralai/codestral-2501",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-codestral-2508",
    provider: "openrouter",
    name: "Mistral: Codestral 2508",
    apiModelId: "mistralai/codestral-2508",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-devstral-medium-2507",
    provider: "openrouter",
    name: "Mistral: Devstral Medium",
    apiModelId: "mistralai/devstral-medium",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-devstral-small-2507",
    provider: "openrouter",
    name: "Mistral: Devstral Small 1.1",
    apiModelId: "mistralai/devstral-small",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-devstral-small-2505",
    provider: "openrouter",
    name: "Mistral: Devstral Small 2505 (free)",
    apiModelId: "mistralai/devstral-small-2505:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-magistral-medium-2506",
    provider: "openrouter",
    name: "Mistral: Magistral Medium 2506",
    apiModelId: "mistralai/magistral-medium-2506",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-magistral-small-2506",
    provider: "openrouter",
    name: "Mistral: Magistral Small 2506",
    apiModelId: "mistralai/magistral-small-2506",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-ministral-3b",
    provider: "openrouter",
    name: "Mistral: Ministral 3B",
    apiModelId: "mistralai/ministral-3b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-ministral-8b",
    provider: "openrouter",
    name: "Mistral: Ministral 8B",
    apiModelId: "mistralai/ministral-8b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-7b-instruct",
    provider: "openrouter",
    name: "Mistral: Mistral 7B Instruct (free)",
    apiModelId: "mistralai/mistral-7b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-7b-instruct-v0-1",
    provider: "openrouter",
    name: "Mistral: Mistral 7B Instruct v0.1",
    apiModelId: "mistralai/mistral-7b-instruct-v0.1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-7b-instruct-v0-3",
    provider: "openrouter",
    name: "Mistral: Mistral 7B Instruct v0.3",
    apiModelId: "mistralai/mistral-7b-instruct-v0.3",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-medium-3",
    provider: "openrouter",
    name: "Mistral: Mistral Medium 3",
    apiModelId: "mistralai/mistral-medium-3",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-medium-3-1",
    provider: "openrouter",
    name: "Mistral: Mistral Medium 3.1",
    apiModelId: "mistralai/mistral-medium-3.1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-nemo",
    provider: "openrouter",
    name: "Mistral: Mistral Nemo (free)",
    apiModelId: "mistralai/mistral-nemo:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-small-24b-instruct-2501",
    provider: "openrouter",
    name: "Mistral: Mistral Small 3 (free)",
    apiModelId: "mistralai/mistral-small-24b-instruct-2501:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-small-3-1-24b-instruct-2503",
    provider: "openrouter",
    name: "Mistral: Mistral Small 3.1 24B (free)",
    apiModelId: "mistralai/mistral-small-3.1-24b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-small-3-2-24b-instruct-2506",
    provider: "openrouter",
    name: "Mistral: Mistral Small 3.2 24B (free)",
    apiModelId: "mistralai/mistral-small-3.2-24b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mixtral-8x22b-instruct",
    provider: "openrouter",
    name: "Mistral: Mixtral 8x22B Instruct",
    apiModelId: "mistralai/mixtral-8x22b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mixtral-8x7b-instruct",
    provider: "openrouter",
    name: "Mistral: Mixtral 8x7B Instruct",
    apiModelId: "mistralai/mixtral-8x7b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-pixtral-12b",
    provider: "openrouter",
    name: "Mistral: Pixtral 12B",
    apiModelId: "mistralai/pixtral-12b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-pixtral-large-2411",
    provider: "openrouter",
    name: "Mistral: Pixtral Large 2411",
    apiModelId: "mistralai/pixtral-large-2411",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-mistralai-mistral-saba-2502",
    provider: "openrouter",
    name: "Mistral: Saba",
    apiModelId: "mistralai/mistral-saba",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-moonshotai-kimi-dev-72b",
    provider: "openrouter",
    name: "MoonshotAI: Kimi Dev 72B (free)",
    apiModelId: "moonshotai/kimi-dev-72b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-moonshotai-kimi-k2",
    provider: "openrouter",
    name: "MoonshotAI: Kimi K2 0711 (free)",
    apiModelId: "moonshotai/kimi-k2:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-moonshotai-kimi-k2-0905",
    provider: "openrouter",
    name: "MoonshotAI: Kimi K2 0905",
    apiModelId: "moonshotai/kimi-k2-0905",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-moonshotai-kimi-vl-a3b-thinking",
    provider: "openrouter",
    name: "MoonshotAI: Kimi VL A3B Thinking (free)",
    apiModelId: "moonshotai/kimi-vl-a3b-thinking:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-morph-morph-v3-fast",
    provider: "openrouter",
    name: "Morph: Morph V3 Fast",
    apiModelId: "morph/morph-v3-fast",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-morph-morph-v3-large",
    provider: "openrouter",
    name: "Morph: Morph V3 Large",
    apiModelId: "morph/morph-v3-large",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-gryphe-mythomax-l2-13b",
    provider: "openrouter",
    name: "MythoMax 13B",
    apiModelId: "gryphe/mythomax-l2-13b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-neversleep-llama-3-lumimaid-70b",
    provider: "openrouter",
    name: "NeverSleep: Llama 3 Lumimaid 70B",
    apiModelId: "neversleep/llama-3-lumimaid-70b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-neversleep-llama-3-1-lumimaid-8b",
    provider: "openrouter",
    name: "NeverSleep: Lumimaid v0.2 8B",
    apiModelId: "neversleep/llama-3.1-lumimaid-8b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-neversleep-noromaid-20b",
    provider: "openrouter",
    name: "Noromaid 20B",
    apiModelId: "neversleep/noromaid-20b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nousresearch-deephermes-3-llama-3-8b-preview",
    provider: "openrouter",
    name: "Nous: DeepHermes 3 Llama 3 8B Preview (free)",
    apiModelId: "nousresearch/deephermes-3-llama-3-8b-preview:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nousresearch-deephermes-3-mistral-24b-preview",
    provider: "openrouter",
    name: "Nous: DeepHermes 3 Mistral 24B Preview",
    apiModelId: "nousresearch/deephermes-3-mistral-24b-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nousresearch-hermes-3-llama-3-1-405b",
    provider: "openrouter",
    name: "Nous: Hermes 3 405B Instruct",
    apiModelId: "nousresearch/hermes-3-llama-3.1-405b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nousresearch-hermes-3-llama-3-1-70b",
    provider: "openrouter",
    name: "Nous: Hermes 3 70B Instruct",
    apiModelId: "nousresearch/hermes-3-llama-3.1-70b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nousresearch-hermes-4-405b",
    provider: "openrouter",
    name: "Nous: Hermes 4 405B",
    apiModelId: "nousresearch/hermes-4-405b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nousresearch-hermes-4-70b",
    provider: "openrouter",
    name: "Nous: Hermes 4 70B",
    apiModelId: "nousresearch/hermes-4-70b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nousresearch-hermes-2-pro-llama-3-8b",
    provider: "openrouter",
    name: "NousResearch: Hermes 2 Pro - Llama-3 8B",
    apiModelId: "nousresearch/hermes-2-pro-llama-3-8b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nvidia-llama-3-1-nemotron-70b-instruct",
    provider: "openrouter",
    name: "NVIDIA: Llama 3.1 Nemotron 70B Instruct",
    apiModelId: "nvidia/llama-3.1-nemotron-70b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nvidia-llama-3-1-nemotron-ultra-253b-v1",
    provider: "openrouter",
    name: "NVIDIA: Llama 3.1 Nemotron Ultra 253B v1",
    apiModelId: "nvidia/llama-3.1-nemotron-ultra-253b-v1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-nvidia-nemotron-nano-9b-v2",
    provider: "openrouter",
    name: "NVIDIA: Nemotron Nano 9B V2 (free)",
    apiModelId: "nvidia/nemotron-nano-9b-v2:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-chatgpt-4o-latest",
    provider: "openrouter",
    name: "OpenAI: ChatGPT-4o",
    apiModelId: "openai/chatgpt-4o-latest",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-codex-mini",
    provider: "openrouter",
    name: "OpenAI: Codex Mini",
    apiModelId: "openai/codex-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-3-5-turbo",
    provider: "openrouter",
    name: "OpenAI: GPT-3.5 Turbo",
    apiModelId: "openai/gpt-3.5-turbo",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-3-5-turbo-0613",
    provider: "openrouter",
    name: "OpenAI: GPT-3.5 Turbo (older v0613)",
    apiModelId: "openai/gpt-3.5-turbo-0613",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-3-5-turbo-16k",
    provider: "openrouter",
    name: "OpenAI: GPT-3.5 Turbo 16k",
    apiModelId: "openai/gpt-3.5-turbo-16k",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-3-5-turbo-instruct",
    provider: "openrouter",
    name: "OpenAI: GPT-3.5 Turbo Instruct",
    apiModelId: "openai/gpt-3.5-turbo-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4",
    provider: "openrouter",
    name: "OpenAI: GPT-4",
    apiModelId: "openai/gpt-4",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4-0314",
    provider: "openrouter",
    name: "OpenAI: GPT-4 (older v0314)",
    apiModelId: "openai/gpt-4-0314",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4-turbo",
    provider: "openrouter",
    name: "OpenAI: GPT-4 Turbo",
    apiModelId: "openai/gpt-4-turbo",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4-1106-preview",
    provider: "openrouter",
    name: "OpenAI: GPT-4 Turbo (older v1106)",
    apiModelId: "openai/gpt-4-1106-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4-turbo-preview",
    provider: "openrouter",
    name: "OpenAI: GPT-4 Turbo Preview",
    apiModelId: "openai/gpt-4-turbo-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4-1-2025-04-14",
    provider: "openrouter",
    name: "OpenAI: GPT-4.1",
    apiModelId: "openai/gpt-4.1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4-1-mini-2025-04-14",
    provider: "openrouter",
    name: "OpenAI: GPT-4.1 Mini",
    apiModelId: "openai/gpt-4.1-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4-1-nano-2025-04-14",
    provider: "openrouter",
    name: "OpenAI: GPT-4.1 Nano",
    apiModelId: "openai/gpt-4.1-nano",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4o",
    provider: "openrouter",
    name: "OpenAI: GPT-4o",
    apiModelId: "openai/gpt-4o",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4o-2024-05-13",
    provider: "openrouter",
    name: "OpenAI: GPT-4o (2024-05-13)",
    apiModelId: "openai/gpt-4o-2024-05-13",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4o-2024-08-06",
    provider: "openrouter",
    name: "OpenAI: GPT-4o (2024-08-06)",
    apiModelId: "openai/gpt-4o-2024-08-06",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4o-2024-11-20",
    provider: "openrouter",
    name: "OpenAI: GPT-4o (2024-11-20)",
    apiModelId: "openai/gpt-4o-2024-11-20",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4o-audio-preview",
    provider: "openrouter",
    name: "OpenAI: GPT-4o Audio",
    apiModelId: "openai/gpt-4o-audio-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4o-search-preview-2025-03-11",
    provider: "openrouter",
    name: "OpenAI: GPT-4o Search Preview",
    apiModelId: "openai/gpt-4o-search-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4o-mini",
    provider: "openrouter",
    name: "OpenAI: GPT-4o-mini",
    apiModelId: "openai/gpt-4o-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4o-mini-2024-07-18",
    provider: "openrouter",
    name: "OpenAI: GPT-4o-mini (2024-07-18)",
    apiModelId: "openai/gpt-4o-mini-2024-07-18",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-4o-mini-search-preview-2025-03-11",
    provider: "openrouter",
    name: "OpenAI: GPT-4o-mini Search Preview",
    apiModelId: "openai/gpt-4o-mini-search-preview",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-5-2025-08-07",
    provider: "openrouter",
    name: "OpenAI: GPT-5",
    apiModelId: "openai/gpt-5",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-5-chat-2025-08-07",
    provider: "openrouter",
    name: "OpenAI: GPT-5 Chat",
    apiModelId: "openai/gpt-5-chat",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-5-codex",
    provider: "openrouter",
    name: "OpenAI: GPT-5 Codex",
    apiModelId: "openai/gpt-5-codex",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-5-mini-2025-08-07",
    provider: "openrouter",
    name: "OpenAI: GPT-5 Mini",
    apiModelId: "openai/gpt-5-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-5-nano-2025-08-07",
    provider: "openrouter",
    name: "OpenAI: GPT-5 Nano",
    apiModelId: "openai/gpt-5-nano",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-oss-120b",
    provider: "openrouter",
    name: "OpenAI: gpt-oss-120b (free)",
    apiModelId: "openai/gpt-oss-120b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-gpt-oss-20b",
    provider: "openrouter",
    name: "OpenAI: gpt-oss-20b (free)",
    apiModelId: "openai/gpt-oss-20b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o1-2024-12-17",
    provider: "openrouter",
    name: "OpenAI: o1",
    apiModelId: "openai/o1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o1-mini",
    provider: "openrouter",
    name: "OpenAI: o1-mini",
    apiModelId: "openai/o1-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o1-mini-2024-09-12",
    provider: "openrouter",
    name: "OpenAI: o1-mini (2024-09-12)",
    apiModelId: "openai/o1-mini-2024-09-12",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o1-pro",
    provider: "openrouter",
    name: "OpenAI: o1-pro",
    apiModelId: "openai/o1-pro",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o3-2025-04-16",
    provider: "openrouter",
    name: "OpenAI: o3",
    apiModelId: "openai/o3",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o3-mini-2025-01-31",
    provider: "openrouter",
    name: "OpenAI: o3 Mini",
    apiModelId: "openai/o3-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o3-mini-high-2025-01-31",
    provider: "openrouter",
    name: "OpenAI: o3 Mini High",
    apiModelId: "openai/o3-mini-high",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o3-pro-2025-06-10",
    provider: "openrouter",
    name: "OpenAI: o3 Pro",
    apiModelId: "openai/o3-pro",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o4-mini-2025-04-16",
    provider: "openrouter",
    name: "OpenAI: o4 Mini",
    apiModelId: "openai/o4-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-openai-o4-mini-high-2025-04-16",
    provider: "openrouter",
    name: "OpenAI: o4 Mini High",
    apiModelId: "openai/o4-mini-high",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-opengvlab-internvl3-78b",
    provider: "openrouter",
    name: "OpenGVLab: InternVL3 78B",
    apiModelId: "opengvlab/internvl3-78b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-perplexity-r1-1776",
    provider: "openrouter",
    name: "Perplexity: R1 1776",
    apiModelId: "perplexity/r1-1776",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-perplexity-sonar",
    provider: "openrouter",
    name: "Perplexity: Sonar",
    apiModelId: "perplexity/sonar",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-perplexity-sonar-deep-research",
    provider: "openrouter",
    name: "Perplexity: Sonar Deep Research",
    apiModelId: "perplexity/sonar-deep-research",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-perplexity-sonar-pro",
    provider: "openrouter",
    name: "Perplexity: Sonar Pro",
    apiModelId: "perplexity/sonar-pro",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-perplexity-sonar-reasoning",
    provider: "openrouter",
    name: "Perplexity: Sonar Reasoning",
    apiModelId: "perplexity/sonar-reasoning",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-perplexity-sonar-reasoning-pro",
    provider: "openrouter",
    name: "Perplexity: Sonar Reasoning Pro",
    apiModelId: "perplexity/sonar-reasoning-pro",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-plus-2025-07-28",
    provider: "openrouter",
    name: "Qwen: Qwen Plus 0728",
    apiModelId: "qwen/qwen-plus-2025-07-28",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-vl-max-2025-01-25",
    provider: "openrouter",
    name: "Qwen: Qwen VL Max",
    apiModelId: "qwen/qwen-vl-max",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-vl-plus",
    provider: "openrouter",
    name: "Qwen: Qwen VL Plus",
    apiModelId: "qwen/qwen-vl-plus",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-max-2025-01-25",
    provider: "openrouter",
    name: "Qwen: Qwen-Max ",
    apiModelId: "qwen/qwen-max",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-plus-2025-01-25",
    provider: "openrouter",
    name: "Qwen: Qwen-Plus",
    apiModelId: "qwen/qwen-plus",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-turbo-2024-11-01",
    provider: "openrouter",
    name: "Qwen: Qwen-Turbo",
    apiModelId: "qwen/qwen-turbo",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen2-5-vl-32b-instruct",
    provider: "openrouter",
    name: "Qwen: Qwen2.5 VL 32B Instruct (free)",
    apiModelId: "qwen/qwen2.5-vl-32b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen2-5-vl-72b-instruct",
    provider: "openrouter",
    name: "Qwen: Qwen2.5 VL 72B Instruct (free)",
    apiModelId: "qwen/qwen2.5-vl-72b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-2-vl-7b-instruct",
    provider: "openrouter",
    name: "Qwen: Qwen2.5-VL 7B Instruct",
    apiModelId: "qwen/qwen-2.5-vl-7b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-14b-04-28",
    provider: "openrouter",
    name: "Qwen: Qwen3 14B (free)",
    apiModelId: "qwen/qwen3-14b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-235b-a22b-04-28",
    provider: "openrouter",
    name: "Qwen: Qwen3 235B A22B (free)",
    apiModelId: "qwen/qwen3-235b-a22b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-235b-a22b-07-25",
    provider: "openrouter",
    name: "Qwen: Qwen3 235B A22B Instruct 2507",
    apiModelId: "qwen/qwen3-235b-a22b-2507",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-235b-a22b-thinking-2507",
    provider: "openrouter",
    name: "Qwen: Qwen3 235B A22B Thinking 2507",
    apiModelId: "qwen/qwen3-235b-a22b-thinking-2507",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-30b-a3b-04-28",
    provider: "openrouter",
    name: "Qwen: Qwen3 30B A3B (free)",
    apiModelId: "qwen/qwen3-30b-a3b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-30b-a3b-instruct-2507",
    provider: "openrouter",
    name: "Qwen: Qwen3 30B A3B Instruct 2507",
    apiModelId: "qwen/qwen3-30b-a3b-instruct-2507",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-30b-a3b-thinking-2507",
    provider: "openrouter",
    name: "Qwen: Qwen3 30B A3B Thinking 2507",
    apiModelId: "qwen/qwen3-30b-a3b-thinking-2507",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-32b-04-28",
    provider: "openrouter",
    name: "Qwen: Qwen3 32B",
    apiModelId: "qwen/qwen3-32b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-4b-04-28",
    provider: "openrouter",
    name: "Qwen: Qwen3 4B (free)",
    apiModelId: "qwen/qwen3-4b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-8b-04-28",
    provider: "openrouter",
    name: "Qwen: Qwen3 8B (free)",
    apiModelId: "qwen/qwen3-8b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-coder-30b-a3b-instruct",
    provider: "openrouter",
    name: "Qwen: Qwen3 Coder 30B A3B Instruct",
    apiModelId: "qwen/qwen3-coder-30b-a3b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-coder-480b-a35b-07-25",
    provider: "openrouter",
    name: "Qwen: Qwen3 Coder 480B A35B (free)",
    apiModelId: "qwen/qwen3-coder:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-coder-flash",
    provider: "openrouter",
    name: "Qwen: Qwen3 Coder Flash",
    apiModelId: "qwen/qwen3-coder-flash",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-coder-plus",
    provider: "openrouter",
    name: "Qwen: Qwen3 Coder Plus",
    apiModelId: "qwen/qwen3-coder-plus",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-max",
    provider: "openrouter",
    name: "Qwen: Qwen3 Max",
    apiModelId: "qwen/qwen3-max",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-next-80b-a3b-instruct-2509",
    provider: "openrouter",
    name: "Qwen: Qwen3 Next 80B A3B Instruct",
    apiModelId: "qwen/qwen3-next-80b-a3b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen3-vl-235b-a22b-instruct",
    provider: "openrouter",
    name: "Qwen: Qwen3 VL 235B A22B Instruct",
    apiModelId: "qwen/qwen3-vl-235b-a22b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwq-32b",
    provider: "openrouter",
    name: "Qwen: QwQ 32B",
    apiModelId: "qwen/qwq-32b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-2-5-72b-instruct",
    provider: "openrouter",
    name: "Qwen2.5 72B Instruct (free)",
    apiModelId: "qwen/qwen-2.5-72b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-2-5-7b-instruct",
    provider: "openrouter",
    name: "Qwen2.5 7B Instruct",
    apiModelId: "qwen/qwen-2.5-7b-instruct",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-qwen-qwen-2-5-coder-32b-instruct",
    provider: "openrouter",
    name: "Qwen2.5 Coder 32B Instruct (free)",
    apiModelId: "qwen/qwen-2.5-coder-32b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-relace-relace-apply-3",
    provider: "openrouter",
    name: "Relace: Relace Apply 3",
    apiModelId: "relace/relace-apply-3",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-undi95-remm-slerp-l2-13b",
    provider: "openrouter",
    name: "ReMM SLERP 13B",
    apiModelId: "undi95/remm-slerp-l2-13b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-sao10k-l3-lunaris-8b",
    provider: "openrouter",
    name: "Sao10K: Llama 3 8B Lunaris",
    apiModelId: "sao10k/l3-lunaris-8b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-sao10k-l3-euryale-70b",
    provider: "openrouter",
    name: "Sao10k: Llama 3 Euryale 70B v2.1",
    apiModelId: "sao10k/l3-euryale-70b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-sao10k-l3-1-euryale-70b",
    provider: "openrouter",
    name: "Sao10K: Llama 3.1 Euryale 70B v2.2",
    apiModelId: "sao10k/l3.1-euryale-70b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-sao10k-l3-3-euryale-70b-v2-3",
    provider: "openrouter",
    name: "Sao10K: Llama 3.3 Euryale 70B",
    apiModelId: "sao10k/l3.3-euryale-70b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-shisa-ai-shisa-v2-llama3-3-70b",
    provider: "openrouter",
    name: "Shisa AI: Shisa V2 Llama 3.3 70B  (free)",
    apiModelId: "shisa-ai/shisa-v2-llama3.3-70b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-raifle-sorcererlm-8x22b",
    provider: "openrouter",
    name: "SorcererLM 8x22B",
    apiModelId: "raifle/sorcererlm-8x22b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-stepfun-ai-step3",
    provider: "openrouter",
    name: "StepFun: Step3",
    apiModelId: "stepfun-ai/step3",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-switchpoint-router",
    provider: "openrouter",
    name: "Switchpoint Router",
    apiModelId: "switchpoint/router",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-tencent-hunyuan-a13b-instruct",
    provider: "openrouter",
    name: "Tencent: Hunyuan A13B Instruct (free)",
    apiModelId: "tencent/hunyuan-a13b-instruct:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-thedrummer-anubis-70b-v1-1",
    provider: "openrouter",
    name: "TheDrummer: Anubis 70B V1.1",
    apiModelId: "thedrummer/anubis-70b-v1.1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-thedrummer-cydonia-24b-v4-1",
    provider: "openrouter",
    name: "TheDrummer: Cydonia 24B V4.1",
    apiModelId: "thedrummer/cydonia-24b-v4.1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-thedrummer-rocinante-12b",
    provider: "openrouter",
    name: "TheDrummer: Rocinante 12B",
    apiModelId: "thedrummer/rocinante-12b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-thedrummer-skyfall-36b-v2",
    provider: "openrouter",
    name: "TheDrummer: Skyfall 36B V2",
    apiModelId: "thedrummer/skyfall-36b-v2",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-thedrummer-unslopnemo-12b",
    provider: "openrouter",
    name: "TheDrummer: UnslopNemo 12B",
    apiModelId: "thedrummer/unslopnemo-12b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-thudm-glm-z1-32b-0414",
    provider: "openrouter",
    name: "THUDM: GLM Z1 32B",
    apiModelId: "thudm/glm-z1-32b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-tngtech-deepseek-r1t-chimera",
    provider: "openrouter",
    name: "TNG: DeepSeek R1T Chimera (free)",
    apiModelId: "tngtech/deepseek-r1t-chimera:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-tngtech-deepseek-r1t2-chimera",
    provider: "openrouter",
    name: "TNG: DeepSeek R1T2 Chimera (free)",
    apiModelId: "tngtech/deepseek-r1t2-chimera:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-alibaba-tongyi-deepresearch-30b-a3b",
    provider: "openrouter",
    name: "Tongyi DeepResearch 30B A3B (free)",
    apiModelId: "alibaba/tongyi-deepresearch-30b-a3b:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-venice-uncensored",
    provider: "openrouter",
    name: "Venice: Uncensored (free)",
    apiModelId: "cognitivecomputations/dolphin-mistral-24b-venice-edition:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-microsoft-wizardlm-2-8x22b",
    provider: "openrouter",
    name: "WizardLM-2 8x22B",
    apiModelId: "microsoft/wizardlm-2-8x22b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-x-ai-grok-3",
    provider: "openrouter",
    name: "xAI: Grok 3",
    apiModelId: "x-ai/grok-3",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-x-ai-grok-3-beta",
    provider: "openrouter",
    name: "xAI: Grok 3 Beta",
    apiModelId: "x-ai/grok-3-beta",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-x-ai-grok-3-mini",
    provider: "openrouter",
    name: "xAI: Grok 3 Mini",
    apiModelId: "x-ai/grok-3-mini",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-x-ai-grok-3-mini-beta",
    provider: "openrouter",
    name: "xAI: Grok 3 Mini Beta",
    apiModelId: "x-ai/grok-3-mini-beta",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-x-ai-grok-4-07-09",
    provider: "openrouter",
    name: "xAI: Grok 4",
    apiModelId: "x-ai/grok-4",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-x-ai-grok-4-fast",
    provider: "openrouter",
    name: "xAI: Grok 4 Fast (free)",
    apiModelId: "x-ai/grok-4-fast:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-x-ai-grok-code-fast-1",
    provider: "openrouter",
    name: "xAI: Grok Code Fast 1",
    apiModelId: "x-ai/grok-code-fast-1",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-z-ai-glm-4-32b-0414",
    provider: "openrouter",
    name: "Z.AI: GLM 4 32B ",
    apiModelId: "z-ai/glm-4-32b",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-z-ai-glm-4-5",
    provider: "openrouter",
    name: "Z.AI: GLM 4.5",
    apiModelId: "z-ai/glm-4.5",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-z-ai-glm-4-5-air",
    provider: "openrouter",
    name: "Z.AI: GLM 4.5 Air (free)",
    apiModelId: "z-ai/glm-4.5-air:free",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-z-ai-glm-4-5v",
    provider: "openrouter",
    name: "Z.AI: GLM 4.5V",
    apiModelId: "z-ai/glm-4.5v",
    hasReasoning: false,
    canDisableThinking: false,
  },
  {
    id: "openrouter-z-ai-glm-4-6",
    provider: "openrouter",
    name: "Z.AI: GLM 4.6",
    apiModelId: "z-ai/glm-4.6",
    hasReasoning: false,
    canDisableThinking: false,
  },
];

export function listModels() {
  return MODELS;
}

export function listModelsByProvider(provider: SettingsProvider) {
  return MODELS.filter((model) => model.provider === provider);
}

export function findModelById(id: string) {
  return MODELS.find((model) => model.id === id);
}

export function modelSupportsReasoning(model: ProviderModel): boolean {
  return model.hasReasoning;
}

