name: Fetch Models Nightly

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  fetch-models:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install

      - name: Fetch models
        run: node scripts/fetch-models.mjs

      - name: Check for changes
        id: changes
        run: |
          if git diff --quiet src/lib/list-model.ts; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: steps.changes.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update AI models list'
          title: 'Update AI Models List'
          body: |
            Automated update of AI models from Chatwise and OpenRouter APIs.

            This PR was automatically generated by the nightly fetch-models workflow.

            **Last updated:** ${{ github.run_id }}
          branch: update-models
          delete-branch: true
          add-paths: |
            src/lib/list-model.ts
          labels: |
            automated
            dependencies
